### ISSUE TITLE
Spine 3.7 incompatibility

### ISSUE THREAD

**Issue by stoic-john** [heavybullets/PaperZDForSpine2D#1]
PaperZDForSpace2D is currently incompatible with Spine 3.7 tip.  I'm not too familiar with the changes to Spine which cause these errors.
```
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(52): error C2660: 'USpineAtlasAsset::GetAtlas': function does not take 1 arguments
2>...\SpinePlugin\Source\SpinePlugin\Public\SpineAtlasAsset.h(42): note: see declaration of 'USpineAtlasAsset::GetAtlas'
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(52): error C2660: 'USpineSkeletonDataAsset::GetSkeletonData': function does not take 2 arguments
2>...\spineplugin\source\spineplugin\public\SpineSkeletonDataAsset.h(57): note: see declaration of 'USpineSkeletonDataAsset::GetSkeletonData'
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(69): error C2039: 'GetSkeleton': is not a member of 'USpineSkeletonRendererComponent'
2>...\SpinePlugin\Source\SpinePlugin\Public\SpineSkeletonRendererComponent.h(40): note: see declaration of 'USpineSkeletonRendererComponent'
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(94): error C2039: 'UpdateRenderer': is not a member of 'USpineSkeletonRendererComponent'
2>...\SpinePlugin\Source\SpinePlugin\Public\SpineSkeletonRendererComponent.h(40): note: see declaration of 'USpineSkeletonRendererComponent'
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(125): error C2039: 'SetSkeleton': is not a member of 'USpineSkeletonRendererComponent'
2>...\SpinePlugin\Source\SpinePlugin\Public\SpineSkeletonRendererComponent.h(40): note: see declaration of 'USpineSkeletonRendererComponent'
2>...\PaperZDForSpine2D\Source\PaperZDForSpine2D\Private\PaperZDAnimSequence_Spine2D.cpp(135): error C2039: 'SetSkeleton': is not a member of 'USpineSkeletonRendererComponent'
2>...\SpinePlugin\Source\SpinePlugin\Public\SpineSkeletonRendererComponent.h(40): note: see declaration of 'USpineSkeletonRendererComponent'```

**Comment by heavybullets** [comment]
Thanks for pointing that out... i'll check the new Spine2D release and provide a fix as soon as posible

**Comment by heavybullets** [comment]
Hey, just checked the issues... it seems that the guys at Spine2D reverted the update i did and completelly broke the plugin.. i'll have to request them to fix that

**Comment by heavybullets** [comment]
Hey, just checked the issues... it seems that the guys at Spine2D reverted the update i did and completelly broke the plugin.. it seems a commit they made overwrote a big chunk of my changes to the official repo.

For the moment, you can use my Spine branch, which holds the last commit I made that its fully functional.

NOTE: After they fix the issue on Esoteric's github, i'll check how i can update the codebase on this plugin to account for the GetAsset and GetSkeletonData methods.

NOTE2: Remember that blending isn't available on PaperZD for the moment, i'll get to that on next update, but first i have to solve some issues.

I'll close this  issue for now, as it isn't really an issue on our end, but will update this plugin when the change is done in their end.

Cheers

P.S.
https://github.com/heavybullets/spine-runtimes/tree/ue4_paperzdsupport

**Comment by stoic-john** [comment]
Thanks @heavybullets excellent work :)
